### ISSUE TITLE
importerror: no module named qpsnr

### ISSUE THREAD

**Issue by Svyatk0** [MarcAntoine-Arnaud/wisual#1]
Hi Guys. 
I am quite new to Python, and so trying to get this setup working is quite a challenge. It would be great to have a list of requirements if not a basic guide on how to get this started, as the project sounds very interesting. 

Anyways, I figured that this needs to be used with Python 2.7, and not 3.6, but now that I am passed v3,6 issues I have an issue in 2.7 version where its complaining about "qpsnr" module. 
I cant find the module itself in the package. Is this something that needs to be added separately ? 

Any help would be appreciated. 

Thanks

Svyatko

**Comment by MarcAntoine-Arnaud** [comment]
Hello,

Thanks for the interest 👍 
I don't develop anymore this project, but you can test it of course !

To enable qpsnr module, you need to compile the [qpsnr](https://github.com/MarcAntoine-Arnaud/qpsnr) project.
When it's builded, if Wisual still to mention unknown qpsnr module, please check your PYTHONPATH env var.

If you are more confortable with docker, I can test to generate a docker image if you're interested.
And if you wanna to go further with measurement, I'm currently building better framework. I can give you more informations if let me a message on my mailbox: arnaud.marcantoine@gmail.com.

Best,
Marc-Antoine

**Comment by MarcAntoine-Arnaud** [comment]
Hi again,

I generated a first version of the docker container.
You can found informations here: https://hub.docker.com/r/arnaudmarcantoine/wisual/
Tell me if it's works.

Actually some features are missing:
- bad multi-threaded server to switch on UI when a process is in progress (an incopatibility with thread enable block that)
- browser can only show the current level
- missing zoom to results chart

alls other inputs are welcome
Marc-Antoine

**Comment by Svyatk0** [comment]
Thanks. I will give it a go.

svyatko

**Comment by Svyatk0** [comment]
Hiya MarcAntoine

Container loaded, GUI works, I have managed to mound data and results storage locations.
I can see the files in the GUI. I am using the YUV files for the source and compared file. All good BUT when starting the analysis, I see the following output in the console :

172.17.0.1 - - [13/Jul/2017 15:26:22] "POST /job HTTP/1.1" 200 -
[IMGUTILS @ 0x7fb5cca54bf0] Picture size 0x0 is invalid
Unhandled exception in thread started by <bound method QpsnrProcessor.run of <wisual.QpsnrProcessor.QpsnrProcessor object at 0x7fb5cca
78850>>
Traceback (most recent call last):
  File "/wisual/wisual/QpsnrProcessor.py", line 24, in run
    processor = qpsnr.Qpsnr(str(self.outputFile), str(referenceVideo))
  File "/usr/lib/python2.7/site-packages/qpsnr/qpsnr.py", line 288, in __init__
    this = _qpsnr.new_Qpsnr(*args)
RuntimeError: Can't open file

And that’s it. GUI doesn’t report any issues, it just shows the job as Processing, but looking at container stats and Top, it doesn’t look like anything is happening.

Data folders I am using to map to the container have full access permissions for all users, so permissions are unlikely to be an issue.

Have you seen this before ?

Thanks

Svyatko

**Comment by MarcAntoine-Arnaud** [comment]
Hi,
Sorry for the delay...

The message "Picture size 0x0 is invalid" means your YUV has no image size in it.
Is it possible to test with some file tests like them: https://peach.blender.org/download/ ?

Is it possible for you to share a small example of your YUV file ?

Marc-Antoine

**Comment by Svyatk0** [comment]
Hiya.

After playing around I have discovered that standalone qpsnr also doesn’t like YUV files. So that’s where the issue lies. And I dont see how easily that is to fix.

The sample YUV420 can be found here. https://1drv.ms/u/s!Ar_ePfSDBV8x75M_j3QenjhLt_lQFg

I have managed to successfully tested with the original reference file with .MXF extension as well as transcoded TS files. Everything but YUV seems to work, although the graphs generated are rather odd, even in comparison to the qpsnr output graphs.

So I am trying to figure out what qpsnr command is used in Wisual, and why the results differ from standalone qpsnr.

Thanks
Svyatko

**Comment by MarcAntoine-Arnaud** [comment]
Hi,

To support YUV, I need to add video parameters in the UI to pass at qpsnr (I add issue #2 and #3).
I'll try to upgrade it soon.

For the difference between graphs, I'll try to merge [this commit](https://github.com/kellerkindt/qpsnr/commit/4c3f0ec25cf665d16e9900ab495ce6e0c117d85c) from "kellerkindt" repository.
I'll try also to create a reference batch of files. If you have some sharable, it can be awesome.

Marc-Antoine
